version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle dependencies
      - run:  gradle build sonarqube -Dsonar.projectKey="schehata_shelfy" -Dsonar.organization="schehata" -Dsonar.host.url="https://sonarcloud.io"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
